version: '3.8'

services:
  order-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: java -jar ./app.jar
    ports:
      - "8070:8070"
    image: 'order-service'

    depends_on:
      order-redis:
        condition: service_healthy
      order-database:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-database:5432/order-service-base
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  order-database:
    image: postgres:latest
    container_name: order-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: order-service-base
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: postgres -p 5432

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  order-redis:
    container_name: order-redis
    image: redis:latest
    ports:
      - "6379:6379"

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 2s
      retries: 5

volumes:
  postgres-data:
  redis-data: