server:
  port: "${PORT:8081}"

openapi:
  id: "${API_ID:order-service}"
  title: "${API_TITLE:Order service}"
  description: "${API_DESCRIPTION:order-service description}"

spring:
  application:
    name: order-service
  jpa:
    open-in-view: false
  flyway:
    baseline-on-migrate: true
