server:
  port: 8081

openapi:
  id: ${API_ID:user-service}
  title: ${API_TITLE:User service}
  description: ${API_DESCRIPTION:user-service description}

spring:
  application:
    name: ORDER-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/order-service-base
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true

# Hibernate
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000